/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prog2.ups;

import java.io.RandomAccessFile; //archivo aleatorio
import javax.swing.JOptionPane;  //ventana modal
/**
 *
 * @author Laboratorio 9
 */
public class Ventana1 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblprov = new javax.swing.JLabel();
        lblciu = new javax.swing.JLabel();
        lblhab = new javax.swing.JLabel();
        lblest = new javax.swing.JLabel();
        txtprov = new javax.swing.JTextField();
        txtciu = new javax.swing.JTextField();
        txthab = new javax.swing.JTextField();
        txtest = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        btnleer = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btncerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Datos Personales");

        lblprov.setText("Provincia");

        lblciu.setText("Ciudad");

        lblhab.setText("Num habitantes");

        lblest.setText("Ingresos del estado");

        txtprov.setColumns(20);

        txtciu.setColumns(20);
        txtciu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtciuActionPerformed(evt);
            }
        });

        txthab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthabActionPerformed(evt);
            }
        });

        txtest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestActionPerformed(evt);
            }
        });

        btnguardar.setText("Guardar");
        btnguardar.setActionCommand("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnleer.setText("Leer");

        btnlimpiar.setText("Limpiar");

        btncerrar.setText("Cerrar");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblprov)
                    .addComponent(lblest)
                    .addComponent(lblhab)
                    .addComponent(lblciu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtprov)
                    .addComponent(txthab)
                    .addComponent(txtest)
                    .addComponent(txtciu))
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnguardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnleer)
                .addGap(18, 18, 18)
                .addComponent(btnlimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprov)
                    .addComponent(txtprov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblciu)
                    .addComponent(txtciu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhab)
                    .addComponent(txthab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblest)
                    .addComponent(txtest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar)
                    .addComponent(btnleer)
                    .addComponent(btnlimpiar)
                    .addComponent(btncerrar))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtciuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtciuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtciuActionPerformed

    private void txtestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestActionPerformed

    private void txthabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthabActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        try
        {
          RandomAccessFile f;
          f= new RandomAccessFile("c:/intrl/dato.pr2","rw");
          
          String provincia, ciudad;
          int hab;
          double est;
          
          provincia= txtprov.getText();
          ciudad= txtciu.getText();
          //numhab= txtnumlab.getText();    // por que error
          // numhab es int, txtnumhab.getText() es texto
          
          // Conversion
          

          hab=Integer.parseInt(txthab.getText());          
          
          est= Double.parseDouble(txtest.getText());
          // hasta aqui venta modales
          
          
          //Ahora archivos
          f.seek(0);
          f.writeBytes(provincia+"\n");
          
          f.seek(20);
          f.writeInt(hab);
          
          f.seek(24);
          f.writeBytes(ciudad+"\n");
          
          f.seek(44);
          f.writeDouble(est);
          
          JOptionPane.showMessageDialog(rootPane, "guardado ok");
         
          
          f.close();
          
        }catch( Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btncerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnleer;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JLabel lblciu;
    private javax.swing.JLabel lblest;
    private javax.swing.JLabel lblhab;
    private javax.swing.JLabel lblprov;
    private javax.swing.JTextField txtciu;
    private javax.swing.JTextField txtest;
    private javax.swing.JTextField txthab;
    private javax.swing.JTextField txtprov;
    // End of variables declaration//GEN-END:variables
}
